from pathlib import Path
p=Path(__file__).resolve().parents[1]/'src/dsp/r3_sign_matrix.inc'
a=[0]*16384
for n in range(128):
 for k in range(128):
  tile=(n//32)*4+k//32
  offset=((k%32)//2*32+n%32)*2+k%2
  a[tile*1024+offset]=0xbc00 if (n&k).bit_count()%2 else 0x3c00
assert a.count(0xbc00)==8128
p.write_text('/* Generated by scripts/generate_r3_sign_exp0259.py; exact FP16 signs. */\nstatic const uint16_t qbh_r3_sign_matrix[16384] __attribute__((aligned(128))) = {\n'+''.join('    '+','.join(hex(x) for x in a[i:i+16])+',\n' for i in range(0,len(a),16))+'};\n')
